name: sequence_aware_rich_text_renderer
description: An extended Flutter RichText widget that applies custom properties to the TextSpan of specified character sequences
version: 1.0.2
repository: https://github.com/francis94c/sequence-aware-rich-text-renderer

screenshots:
  - description: Example usage.
    path: screenshots/example.png

environment:
  sdk: ^3.5.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7

topics:
  - flutter
  - richtext
  - render-special-characters
  - render-currency

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
